In [1]:
# Hands-On #2: Matrix Operations in NumPy

import numpy as np

print("="*60)
print("1. Matrix Creation & Basic Operations")
print("="*60)

A = np.array([[2, 1],
              [0, 3]])

B = np.array([[1, 4],
              [2, 5]])

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)

print("\nA + B =\n", A + B)
print("\nTranspose of A (A.T) =\n", A.T)
print("\nMatrix Multiplication (A @ B) =\n", A @ B)

print("\n" + "="*60)
print("2. Identity Matrix & Matrix Inverse")
print("="*60)

I = np.eye(3)
print("3x3 Identity Matrix:\n", I)

A2 = np.array([[2, 1],
               [1, 3]])

A_inv = np.linalg.inv(A2)

print("\nMatrix A2:\n", A2)
print("\nInverse of A2:\n", A_inv)
print("\nVerification (A2 @ A_inv):\n", A2 @ A_inv)

print("\n" + "="*60)
print("3. Solving Ax = b")
print("="*60)

# System:
# 2x + y = 5
# x + 3y = 7

A3 = np.array([[2, 1],
               [1, 3]])

b = np.array([5, 7])

x = np.linalg.solve(A3, b)

print("Coefficient Matrix A:\n", A3)
print("Vector b:", b)
print("Solution x:", x)

print("\nVerification:")
print("A @ x =", A3 @ x)

print("\n" + "="*60)
print("4. Exercise Solution: Product Pricing Problem")
print("="*60)

print("Scenario:")
print("Find prices of Product A, B, and C")

# Let:
# Product A = x
# Product B = y
# Product C = z

# Order 1: 2A + 1B + 1C = 120
# Order 2: 1A + 3B + 2C = 190
# Order 3: 3A + 2B + 2C = 220

A_ex = np.array([
    [2, 1, 1],
    [1, 3, 2],
    [3, 2, 2]
])

b_ex = np.array([120, 190, 220])

prices = np.linalg.solve(A_ex, b_ex)

print("\nCoefficient Matrix:\n", A_ex)
print("\nOrder Totals:", b_ex)

print("\nSolved Product Prices:")
print(f"Product A = ₹{prices[0]:.2f}")
print(f"Product B = ₹{prices[1]:.2f}")
print(f"Product C = ₹{prices[2]:.2f}")

print("\nVerification:")
print("A_ex @ prices =", A_ex @ prices)
print("Expected      =", b_ex)

print("\n" + "="*60)
print("ML Connection")
print("="*60)
print("- Matrices are the foundation of Machine Learning.")
print("- Features and datasets are stored as matrices.")
print("- Always prefer np.linalg.solve() over inv(A) @ b.")
print("- Matrix multiplication powers neural networks.")

1. Matrix Creation & Basic Operations
Matrix A:
 [[2 1]
 [0 3]]

Matrix B:
 [[1 4]
 [2 5]]

A + B =
 [[3 5]
 [2 8]]

Transpose of A (A.T) =
 [[2 0]
 [1 3]]

Matrix Multiplication (A @ B) =
 [[ 4 13]
 [ 6 15]]

2. Identity Matrix & Matrix Inverse
3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Matrix A2:
 [[2 1]
 [1 3]]

Inverse of A2:
 [[ 0.6 -0.2]
 [-0.2  0.4]]

Verification (A2 @ A_inv):
 [[ 1.00000000e+00  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00]]

3. Solving Ax = b
Coefficient Matrix A:
 [[2 1]
 [1 3]]
Vector b: [5 7]
Solution x: [1.6 1.8]

Verification:
A @ x = [5. 7.]

4. Exercise Solution: Product Pricing Problem
Scenario:
Find prices of Product A, B, and C

Coefficient Matrix:
 [[2 1 1]
 [1 3 2]
 [3 2 2]]

Order Totals: [120 190 220]

Solved Product Prices:
Product A = ₹20.00
Product B = ₹10.00
Product C = ₹70.00

Verification:
A_ex @ prices = [120. 190. 220.]
Expected      = [120 190 220]

ML Connection
- Matrices are the foundation of Machine Learning.
-