In [1]:
import pandas as pd
import numpy as np

print("--- Intermediate Pandas Exercise Solution ---")

# ==================================================
# Task 1: Basic Pandas Functions and Converting Arrays
# ==================================================
print("\n--- Task 1 ---")

# 1.1 Series
s1_1 = pd.Series([10, 20, 30, 40, 50])

# 1.2 NumPy Array
np_array1_2 = np.random.randint(1, 101, size=(3,4))

# 1.3 DataFrame
df1_3 = pd.DataFrame(np_array1_2, columns=['A', 'B', 'C', 'D'])

print("Series:")
print(s1_1)

print("\nNumPy Array:")
print(np_array1_2)

print("\nDataFrame:")
print(df1_3)

# ==================================================
# Task 2: Synthetic Data Generation
# ==================================================
print("\n--- Task 2 ---")

np.random.seed(42)

df_sales = pd.DataFrame({
    'Date': pd.date_range('2023-01-01', periods=100),
    'Region': np.random.choice(['East', 'West', 'North', 'South'], 100),
    'Product': np.random.choice(['Laptop', 'Mouse', 'Keyboard', 'Monitor'], 100),
    'Sales': np.random.randint(100, 1001, 100),
    'Quantity': np.random.randint(1, 11, 100)
})

# Introduce NaN values
sales_nan_idx = np.random.choice(df_sales.index, 5, replace=False)
qty_nan_idx = np.random.choice(df_sales.index, 3, replace=False)

df_sales.loc[sales_nan_idx, 'Sales'] = np.nan
df_sales.loc[qty_nan_idx, 'Quantity'] = np.nan

print(df_sales.head())

# ==================================================
# Task 3: Indexing and Slicing
# ==================================================
print("\n--- Task 3 ---")

# 3.1
df3_1 = df_sales[['Region', 'Sales']]

# 3.2
df3_2 = df_sales[df_sales['Product'] == 'Laptop']

# 3.3
df3_3 = df_sales[
    (df_sales['Region'] == 'East') &
    (df_sales['Sales'] > 500)
]

# 3.4
monitor_idx = df_sales[df_sales['Product'] == 'Monitor'].index[0]
val3_4 = df_sales.loc[monitor_idx, 'Sales']

print("Region & Sales:")
print(df3_1.head())

print("\nLaptop Records:")
print(df3_2.head())

print("\nEast Region with Sales > 500:")
print(df3_3.head())

print("\nFirst Monitor Sales Value:", val3_4)

# ==================================================
# Task 4: Data Cleaning
# ==================================================
print("\n--- Task 4 ---")

# 4.1
missing_counts4_1 = df_sales.isnull().sum()

# 4.2
df4_2_filled = df_sales.copy()
sales_mean = df4_2_filled['Sales'].mean()
df4_2_filled['Sales'] = df4_2_filled['Sales'].fillna(sales_mean)

# 4.3
df4_3_dropped = df_sales.dropna()

print("Missing Values:")
print(missing_counts4_1)

print("\nFilled Sales NaNs with Mean:")
print(df4_2_filled.head())

print("\nRows After Dropping NaNs:")
print(df4_3_dropped.head())

# ==================================================
# Task 5: Data Manipulation
# ==================================================
print("\n--- Task 5 ---")

# 5.1
df_sales['Total_Revenue'] = (
    df_sales['Sales'] * df_sales['Quantity']
)

# 5.2
df5_2_sorted = df_sales.sort_values(
    by=['Date', 'Sales'],
    ascending=[True, False]
)

# 5.3
df5_3_grouped_region = (
    df_sales.groupby('Region')[['Sales', 'Quantity']]
    .sum()
)

# 5.4
df5_4_grouped_product = (
    df_sales.groupby('Product')['Sales']
    .mean()
)

print("\nData with Total Revenue:")
print(df_sales.head())

print("\nSorted Data:")
print(df5_2_sorted.head())

print("\nRegion-wise Total Sales and Quantity:")
print(df5_3_grouped_region)

print("\nAverage Sales by Product:")
print(df5_4_grouped_product)

print("\nExercise Completed Successfully!")

--- Intermediate Pandas Exercise Solution ---

--- Task 1 ---
Series:
0    10
1    20
2    30
3    40
4    50
dtype: int64

NumPy Array:
[[82 83  7 63]
 [31 76 26 56]
 [83 69 93  9]]

DataFrame:
    A   B   C   D
0  82  83   7  63
1  31  76  26  56
2  83  69  93   9

--- Task 2 ---
        Date Region   Product  Sales  Quantity
0 2023-01-01  North  Keyboard  674.0       7.0
1 2023-01-02  South     Mouse  963.0       4.0
2 2023-01-03   East     Mouse    NaN       7.0
3 2023-01-04  North   Monitor  340.0       8.0
4 2023-01-05  North     Mouse  663.0       1.0

--- Task 3 ---
Region & Sales:
  Region  Sales
0  North  674.0
1  South  963.0
2   East    NaN
3  North  340.0
4  North  663.0

Laptop Records:
         Date Region Product  Sales  Quantity
16 2023-01-17  South  Laptop  624.0       4.0
19 2023-01-20  North  Laptop  798.0      10.0
21 2023-01-22   East  Laptop  185.0       3.0
24 2023-01-25  South  Laptop  781.0       4.0
27 2023-01-28   West  Laptop  745.0       8.0

East Region w